### ISSUE TITLE
Pass versions and parameters to the Python report module

### ISSUE THREAD

**Issue by mantczakaus** [qcif/nf-daff-biosecurity-wf2#15]
* We should also include a VERSION file in the NF workflow that can be passed to the Python modules ([env.sh](http://env.sh/)) to be included in the report.
* Software versions (mafft, blastn, etc.)
* Parameters

**Comment by mantczakaus** [comment]
Partially solved with https://github.com/qcif/nf-daff-biosecurity-wf2/commit/eb4e952ca200186df382f7903325c16861efe258 https://github.com/qcif/nf-daff-biosecurity-wf2/commit/67b5a922e074d1067b2abae46373958428a6f536

**Comment by mantczakaus** [comment]
Hi @neoformit it's ready for you 

[params_2025-05-21_07-47-04.json](https://github.com/user-attachments/files/20374455/params_2025-05-21_07-47-04.json)

software_versions.yml
```
BLAST_BLASTDBCMD:
  blast: 2.16.0+
BLAST_BLASTN:
  blast: 2.16.0+
FASTME:
  fastme: 2.1.6.3
MAFFT_ALIGN:
  mafft: 7.52
Workflow:
    daff/taxassignwf: v0.2.5
    Nextflow: 24.10.6
```
